package com.example.insectdetector.utils

object Constants {
    const val INPUT_SIZE = 224
    const val CONFIDENCE_THRESHOLD = 0.25f
    
    val CLASS_NAMES = listOf(
        "Acherontia atropos",
        "Acherontia atropos(Larve)",
        "Acrosternum millierei",
        "Agrilus hastulifer",
        "Anarsia lineatella",
        "Anoplophora chinensis",
        "Apantesis vittata",
        "Arctia caja(Adult)",
        "Arctia caja(Larve)",
        "Argema mittrei",
        "Argema mittrei(Larve)",
        "Attacus atlas",
        "Cabera variolaria",
        "Cerambyx cerdo",
        "Cerroneuroterus lanuginosus",
        "Cryptolaemus montrouzieri",
        "Curculio glandium",
        "Cydia latiferreana",
        "Cydia pomonella",
        "Danaus plexippus",
        "Deilephila elpenor",
        "Dicranura ulmi",
        "Dicycla oo",
        "Dinoptera collaris",
        "Diprion pini",
        "Epicometis hirta",
        "Euproctis chrysorrhoea",
        "Gypsonoma aceriana",
        "Harpyia milhauseri",
        "Hesperophanes sericeus",
        "Hyles lineata",
        "Hylesinus varius",
        "Lachnus roboris",
        "Lampetis mimosa",
        "Lyctus brunneus",
        "Macroglossum stellatarum",
        "Metamasius hemipterus",
        "Nezara viridula",
        "Nycteola asiatica",
        "Opodiphthera astrophela",
        "Opodiphthera eucalypti",
        "Osphranteria coerulescens",
        "Otiorhynchus sulcatus",
        "Palpita unionalis",
        "Papilio glaucus",
        "Platypus cylindrus",
        "Psalmocharias alhageos",
        "Rhagoletis pomonella",
        "Saturnia pavonia",
        "Schinia arcigera",
        "Sirex noctilio",
        "Smerinthus ocellata",
        "Sphrageidus similis",
        "Spodoptera exigua",
        "Spoladea recurvalis",
        "Stromatium auratum",
        "Synanthedon pyri",
        "Tabanus atratus",
        "Tortrix viridana",
        "Tyria jacobaeae",
        "Tyria jacobaeae(Adult)",
        "Vanessa atalanta",
        "Vespa crabro",
        "Vespula maculifrons",
        "Xanthogaleruca luteola",
        "Xylocopa valga",
        "Yponomeuta padella",
        "Yponomeuta padella(Larve)",
        "Zeuzera pyrina"
    )
}
